### ISSUE TITLE
Maybe a little mention?

### ISSUE THREAD

**Issue by framegrace** [tonymet/gcloud-lite#1]
Hi I was the one that posted this solution on the gsutil issue.
I know in this case, preparing all the distribution pipeline  is not trivial, but making the Dockerfile work wasn't either.... it took quite some time to find the way to disable that python.

So maybe you can add a little mention? It helps on CV's :)

Thanks

**Comment by tonymet** [comment]
thanks for raising and you're right i'll get that added.

**Comment by tonymet** [comment]
Here we go and thanks again for the contribution.  https://github.com/tonymet/gcloud-lite/commit/4e5afef9360d4bcee875410f1e8922226b596a9d

could you check 'gcloud storage list' commands and see if they auto-install "python3-shared" ?  If so I could use help in the necessary config to "trick" gcloud into marking it installed

**Comment by tonymet** [comment]
big thanks for taking the time to find an effective & workable stripping solution to help reduce the bloat. it's clearly been a big issue plaguing many developers .  

I'd love to continue partnering together on this . there's a lot of demand

**Comment by framegrace** [comment]
Yeah, no problem. And thanks for creating this workflow, it didn't even cross my mind to do it, but is cleary needed.

**Comment by tonymet** [comment]
@framegrace thanks for all the help with this. I updated the CI and improved the stripping logic to reduce the size even more.  have a look and let me know what you think
