### ISSUE TITLE
Doc idea

### ISSUE THREAD

**Issue by greenozon** [tonymet/gcloud-lite#4]
Hi!
is it possible to suggest one minor idea for doc purpose?

How about adding an URL to official Google gcloud release notes for each specific build?
here -
![image](https://github.com/user-attachments/assets/62ba87c4-d478-4d87-bb2e-ba9e91099d0c)

so say for latest release 484 the link gonna be
https://cloud.google.com/sdk/docs/release-notes#48400_2024-07-16

thanks!

**Comment by tonymet** [comment]
that's a great idea. let me see where this summary is set and add that link.  great suggestion!

**Comment by tonymet** [comment]
https://github.com/tonymet/gcloud-lite/blob/4e5afef9360d4bcee875410f1e8922226b596a9d/lite-release.sh#L63  i believe it's set here.

**Comment by tonymet** [comment]
i added the generic link for now which includes anchors to the version.  I don't have the release date in scope to build the url fragment e.g. `#48400_2024-07-16` . see the latest release description

**Comment by tonymet** [comment]
![image](https://github.com/user-attachments/assets/5ddf57cd-d8a3-4717-9cc3-c43fe3579956)
